
spring:
    datasource:
        url: jdbc:mysql://localhost:3308/JobUpload?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: Comcast99!
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: true
        hibernate.ddl-auto: update
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.connection.provider_disables_autocommit: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true

